name: flutter_time_until
description: Show the remaining to time to a given date (and time).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+4
repository: https://github.com/gorgtopalski/flutter_time_until

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"